force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/VagaContrato__c.field-meta.xml
<CustomField>
    <fullName>VagaContrato__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vaga de contrato?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PositionUpdateBatchJob.cls
global with sharing class PositionUpdateBatchJob implements Database.Batchable<SObject>{

    //você define a consulta que usará neste contexto de lote 'selecionar ID da conta'
    global Database.QueryLocator start(Database.BatchableContext bc){
        String query = 'SELECT Id, VagaContrato__c, Account__c FROM Position__c WHERE VagaContrato__c = true';
        return Database.getQueryLocator(query);
    }

    //mas recebe apenas uma lista relativamente curta de registros (padrão 200)
    global void execute (Database.BatchableContext bc, List<Position__c> posList){

        // Lista para atualizar vagas
        List<Position__c> posUpdate = new List<Position__c>();

        // Conjunto para armazenar os Ids das contas
        Set<Id> accountsIds = new Set<Id>(); 

        for(Position__c posAcc : posList){

            // Adiciona o Id da conta atual ao conjunto
            accountsIds.add(posAcc.Account__c); 
        }

        Contract[] contracts = [SELECT Id, AccountId, StartDate, EndDate, Status FROM Contract WHERE AccountId = :accountsIds AND Status = 'Activated' LIMIT 1];

        for(Position__c posUp : posList){

            //Contract[] contracts = [SELECT Id, AccountId, StartDate, EndDate, Status FROM Contract WHERE AccountId = :posUp.Account__c AND Status = 'Activated' LIMIT 1];
            if (posUp.VagaContrato__c) {

                if (contracts.isEmpty()) {
                    posUp.Status__c = 'Canceled';
                    posUpdate.add(posUp);

                } 
            }
        }

        update posUpdate;
    }

    // encerra todas as pontas soltas conforme necessário
    global void finish(Database.BatchableContext bc){
        System.debug('Batch position processed!');

    }
}