force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Legacy_Position_Number__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Position_Number__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Position Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Position__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>LATAM</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Pay_Grade__c.field-meta.xml
<CustomField>
    <fullName>Pay_Grade__c</fullName>
    <label>Pay Grade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ENG-100</fullName>
            </value>
            <value>
                <fullName>ENG-200</fullName>
            </value>
            <value>
                <fullName>ENG-300</fullName>
            </value>
            <value>
                <fullName>ENG-400</fullName>
            </value>
            <value>
                <fullName>ACT-100</fullName>
            </value>
            <value>
                <fullName>ACT-200</fullName>
            </value>
            <value>
                <fullName>ACT-300</fullName>
            </value>
            <value>
                <fullName>ACT-400</fullName>
            </value>
            <value>
                <fullName>IT-100</fullName>
            </value>
            <value>
                <fullName>IT-200</fullName>
            </value>
            <value>
                <fullName>IT-300</fullName>
            </value>
            <value>
                <fullName>IT-400</fullName>
            </value>
            <value>
                <fullName>C-100</fullName>
            </value>
            <value>
                <fullName>C-200</fullName>
            </value>
            <value>
                <fullName>C-300</fullName>
            </value>
            <value>
                <fullName>C-400</fullName>
            </value>
            <value>
                <fullName>S-100</fullName>
            </value>
            <value>
                <fullName>S-200</fullName>
            </value>
            <value>
                <fullName>S-300</fullName>
            </value>
            <value>
                <fullName>S-400</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Salary_Range__c.field-meta.xml
<CustomField>
    <fullName>Salary_Range__c</fullName>
    <label>Salary Range</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>50K-75K</fullName>
            </value>
            <value>
                <fullName>75K-90K</fullName>
            </value>
            <value>
                <fullName>90K-120K</fullName>
            </value>
            <value>
                <fullName>120K+</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Skills_Required__c.field-meta.xml
<CustomField>
    <fullName>Skills_Required__c</fullName>
    <label>Skills Required</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/VagaContrato__c.field-meta.xml
<CustomField>
    <fullName>VagaContrato__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Vaga de contrato?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PositionDAO.cls
public with sharing class PositionDAO {

    //pegar lista de positions disponíveis com status igual a New ou Open
    @AuraEnabled
    public static List<Position__c> getPositionsAvailableNotFilter(){

        Set<String> statusValues = new Set<String> {'New', 'Open'};

        return [
                    SELECT Id, Account__c, Account__r.Name, Approval_Status__c, Department__c, Education__c, 
                            Hiring_Manager__c, Job_Description__c, Legacy_Position_Number__c, Location__c, 
                            Name, OwnerId, Owner.Name, Pay_Grade__c, Salary_Range__c, Skills_Required__c, 
                            Status__c, VagaContrato__c 
                    FROM Position__c 
                    WHERE Status__c IN :statusValues
                ];
    }

    //pegar lista de positions disponíveis com status igual a New ou Open
    @AuraEnabled
    public static List<Position__c> getPositionsAvailable(String searchTerm, String selectedStatus){
    
        Set<String> statusValues = new Set<String> {'New', 'Open'};
    
        String query = 'SELECT Id, CreatedDate, Account__c, Account__r.Name, Approval_Status__c, Department__c, Education__c, Hiring_Manager__c, Job_Description__c, Legacy_Position_Number__c, Location__c, Name, OwnerId, Owner.Name, Pay_Grade__c, Salary_Range__c, Skills_Required__c, Status__c, VagaContrato__c ' +
                        'FROM Position__c ' +
                        'WHERE Status__c IN :statusValues';
    
        if (!String.isBlank(searchTerm)) {
            searchTerm = '%' + searchTerm + '%'; 
            query += ' AND (Name LIKE :searchTerm OR Account__r.Name LIKE :searchTerm)';
        }

        if (selectedStatus != 'All') {
            query += ' AND Status__c = :selectedStatus';
        }
    
        return Database.query(query);
    }
    
}