force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PositionController.cls
public with sharing class PositionController {

    //---------------
    //métodos update
    @AuraEnabled
    public static void updatePosition(List<Id> ids, String approvalStatus, String status){

        List<Position__c> positionsUpdate = new List<Position__c>();

        if (ids != null && ids.size()>0) {
            
            for (Id id : ids) {
                Position__c pos = new Position__c();
                pos.Id = id;

                if (!String.isBlank(approvalStatus)) {
                    pos.Approval_Status__c = approvalStatus;
                }

                if (!String.isBlank(status)) {
                    pos.Status__c = status;
                }
                positionsUpdate.add(pos);
            }
        }

        if (positionsUpdate != null && positionsUpdate.size() > 0) {
            update positionsUpdate;
        }
        
    }

    //---------------
    //métodos insert


}