force-app/main/default/objects/Contract/fields/PositionMonth__c.field-meta.xml
<CustomField>
    <fullName>PositionMonth__c</fullName>
    <label>Positions por mês</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/PositionsHomeControllerTest.cls
@isTest
public with sharing class PositionsHomeControllerTest {
    
    @isTest
    static void testGetPositions(){
        
        Position__c[] listPositions = [SELECT Id, Name, Job_Description__c FROM Position__c];
        
        for(Integer i = 1;i <= 20; i++){
            
            Account accNew = new Account();
            accNew.Name = 'Teste Conta ' + i;
            insert accNew;
            
            Contract contrNew = new Contract();
            contrNew.AccountId = accNew.Id;
            contrNew.Status = 'New';
            contrNew.ContractTerm = 1;
            contrNew.StartDate = System.today();
            contrNew.PositionMonth__c = 1;
            insert contrNew;
			contrNew.Status = 'Activated';
            update contrNew;
            
            Position__c posNew = new Position__c();
            posNew.Name = 'Teste Position ' + i;
            posNew.Job_Description__c = 'Description Position ' + i;
            posNew.Account__c = accNew.Id;
            
            listPositions.add(posNew); 
        }
      
        insert listPositions;
                
		Boolean result = PositionsHomeController.getPositions().isEmpty() ? false : true;
        System.assertEquals(true, result);
    }
    
    @isTest
    static void testGetPositionsAndAccount(){
        
        Position__c[] listPositions = [SELECT Id, Name, Job_Description__c, Account__r.Name, Approval_Status__c FROM Position__c];
        
        for(Integer i = 1;i <= 20; i++){
            
            Account accNew = new Account();
            accNew.Name = 'Teste Conta ' + i;
            insert accNew;
            
            Contract contrNew = new Contract();
            contrNew.AccountId = accNew.Id;
            contrNew.Status = 'New';
            contrNew.ContractTerm = 1;
            contrNew.StartDate = System.today();
            contrNew.PositionMonth__c = 1;
            insert contrNew;
			contrNew.Status = 'Activated';
            update contrNew;
            
            Position__c posNew = new Position__c();
            posNew.Name = 'Teste Position ' + i;
            posNew.Job_Description__c = 'Description Position ' + i;
            posNew.Account__c = accNew.Id;
            
            listPositions.add(posNew); 
        }
        
        insert listPositions;
        
        //System.debug(PositionsHomeController.getPositionsAndAccount());
		Boolean result = PositionsHomeController.getPositionsAndAccount().isEmpty() ? false : true;
        System.assertEquals(true, result);
    }


}