force-app/main/default/objects/Contract/fields/PositionMonth__c.field-meta.xml
<CustomField>
    <fullName>PositionMonth__c</fullName>
    <label>Positions por mês</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PositionMonth__c.field-meta.xml
<CustomField>
    <fullName>PositionMonth__c</fullName>
    <label>Positions por mês</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Início do Contrato</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Prazo do contrato (meses)</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Contract.recordType-meta.xml
<RecordType>
    <fullName>Contract</fullName>
    <active>true</active>
    <businessProcess>Contract</businessProcess>
    <label>Contract</label>
</RecordType>

force-app/main/default/classes/OpportunityTestDataFactory.cls
@isTest
public with sharing class OpportunityTestDataFactory {

    //
    public static Opportunity createOpportunitySample(Boolean doInsert, String typeName, Date closeDate, Id accId, String stage){

        RecordType recordType = [SELECT Id FROM RecordType WHERE Name =:typeName LIMIT 1];

        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.RecordTypeId = recordType.Id;
        opp.CloseDate = closeDate;
        opp.AccountId = accId;
        opp.StageName = stage;

        if(doInsert){
            insert opp;
        }
        return opp;
    }

    //
    public static Opportunity createOpportunitySampleContract(Boolean doInsert, Date closeDate, Date startDate, Id accId, String stage){

        RecordType recordType = [SELECT Id FROM RecordType WHERE Name = 'Contract' LIMIT 1];

        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.RecordTypeId = recordType.Id;
        opp.CloseDate = closeDate;
        opp.StartDate__c = startDate;
        opp.AccountId = accId;
        opp.StageName = stage;

        if(doInsert){
            insert opp;
        }
        return opp;
    }

    //
    public static List<Opportunity> createOpportunitySampleList(Boolean doInsert, Integer numOpp){
        
        List<Opportunity> lstOpp = new List<Opportunity>();

        for(Integer i = 1; i <= numOpp; i++) {
            Opportunity opp = new Opportunity();
            opp.Name = 'Test Opportunity ' + i;
            lstOpp.add(opp);
		}

        if(doInsert){
            insert lstOpp;
        }
        return lstOpp;
    }

    //
    public static Opportunity updateOpportunityStatus(Boolean doUpdate, Opportunity opp, String stage){
        
        Opportunity oppUpdate = opp;
        oppUpdate.StageName = stage;
        
        if(doUpdate){
            update oppUpdate;
        }
        return oppUpdate;
    }    

    //
    public static Opportunity updateOpportunityDate(Boolean doUpdate, Opportunity opp, Date startDate){
    
        Opportunity oppUpdate = opp;
        oppUpdate.StartDate__c = startDate;
        
        if(doUpdate){
            update oppUpdate;
        }
        return oppUpdate;
    }  

    //
    public static Opportunity updateOpportunityContract(Boolean doUpdate, Opportunity opp, String stage, Date startDate, Integer posMonth, Integer term){
        
        Opportunity oppUpdate = opp;
        oppUpdate.StageName = stage;
        oppUpdate.StartDate__c = startDate;
        oppUpdate.PositionMonth__c = posMonth;
        oppUpdate.Term__c = term;
        
        if(doUpdate){
            update oppUpdate;
        }
        return oppUpdate;
    }    
}