force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
            <value>
                <fullName>Generate Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTriggerHandler.cls
public with sharing class JobApplicationTriggerHandler {
    
    //Construtor vazio
    public JobApplicationTriggerHandler() {

    }

    //Postar no chatter se for aplicado a vaga quando novo registro
    public void postChatterJob(Map<Id, Job_Application__c> jobsOldMap, Map<Id, Job_Application__c> jobsNewMap){

        List<FeedItem> postsList = new List<FeedItem>();

        // Obtenha os IDs das aplicações de vaga
        Set<Id> jobApplicationIds = new Set<Id>(jobsNewMap.keySet());
        jobApplicationIds.addAll(jobsOldMap.keySet());

        // Consulta para obter os campos relacionados Position__r.Name, Position__r.Status__c e Candidate__c
        List<Job_Application__c> jobApplications = [SELECT Id, Name, Position__r.Name, Position__r.Status__c, Candidate__c, Stage__c,
                                                            CreatedDate, CreatedBy.Name
                                                    FROM Job_Application__c 
                                                    WHERE Id IN :jobApplicationIds];

        for (Job_Application__c jobNew : jobApplications) {

            Id jobId = jobNew.Id;

            if (!jobsOldMap.containsKey(jobId)) {

                FeedItem post = new FeedItem();
                post.ParentId = jobNew.Candidate__c;
                post.Body = 'Nova Aplicação a vaga' + '\n\n' +
                            'Aplicação/Nome da vaga: ' + jobNew.Name + '/' + jobNew.Position__r.Name + '\n' +
                            'Status: ' + jobNew.Position__r.Status__c + '\n' +
                            'Fase: ' + jobNew.Stage__c + '\n' +
                            'Vaga criada no dia: ' + jobNew.CreatedDate + ' por ' + jobNew.CreatedBy.Name;
                postsList.add(post); 
                         
            } else if (jobsOldMap.containsKey(jobId) && jobsOldMap.get(jobId) != jobsNewMap.get(jobId)) {

                FeedItem post = new FeedItem();
                post.ParentId = jobNew.Candidate__c;
                post.Body = 'Atualização da vaga aplicada' + '\n\n' +
                            'Aplicação/Nome da vaga: ' + jobNew.Name + '/' + jobNew.Position__r.Name + '\n' +
                            'Status: ' + jobNew.Position__r.Status__c + '\n' +
                            'Fase: ' + jobNew.Stage__c + '\n' +
                            'Vaga atualizada no dia: ' + jobNew.CreatedDate + ' por ' + jobNew.CreatedBy.Name;
                postsList.add(post); 
            }
        }
        insert postsList;
    }
}