force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interviewer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Date_Time_Interview__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Interview__c</fullName>
    <label>Date and Time of Interview</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Job_Application__c.Stage__c</field>
            <operation>notEqual</operation>
            <value>New, Phone Screen, Schedule Interviews, Closed - Position Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InterviewerTestDataFactory.cls
@isTest
public with sharing class InterviewerTestDataFactory {

    //massa para criar UM único 
    public static Interviewer__c createInterviewer(Boolean doInsert, Id candId, Id jobId, Datetime valueDateTime){
    
        Interviewer__c interviewer  = new Interviewer__c();
        interviewer.Candidate__c = candId;
        interviewer.Job_Application__c = jobId;
        interviewer.Date_Time_Interview__c = valueDateTime;

        if(doInsert){
            insert interviewer;
        }
        return interviewer;
    }  

    //massa para criar uma LISTA 
    public static List<Interviewer__c> createInterviewerList(Boolean doInsert, List<Job_Application__c> lstJobs, Datetime valueDateTime){
        
        List<Interviewer__c> lstInterviewers = new List<Interviewer__c>();

        for (Job_Application__c job : lstJobs) {
            Interviewer__c interviewer = new Interviewer__c();
            interviewer.Job_Application__c = job.Id;
            interviewer.Date_Time_Interview__c = valueDateTime;
            lstInterviewers.add(interviewer);
        }

        if(doInsert){
            insert lstInterviewers;
        }
        return lstInterviewers;
    }

    //massa para atualizar UM único 
    public static Interviewer__c updateInterviewer(Boolean doUpdate, Interviewer__c interviewer){
        
        Interviewer__c interviewerUpdate = interviewer;

        if(doUpdate){
            update interviewerUpdate;
        }
        return interviewerUpdate;
    }
    
    //massa para atualizar uma LISTA 
    public static List<Interviewer__c> updateInterviewerDate(Boolean doUpdate, List<Interviewer__c> lstInterviewers, Datetime valueDateTime){

        List<Interviewer__c> lstInterviewersUpdated = new List<Interviewer__c>();
        
        for (Interviewer__c interviewer : lstInterviewers) {
            interviewer.Date_Time_Interview__c = valueDateTime;
            lstInterviewersUpdated.add(interviewer);
        }

        if(doUpdate){
            update lstInterviewersUpdated;
        }
        return lstInterviewersUpdated;
    }

    //massa para atualizar uma LISTA 
    public static List<Interviewer__c> updateInterviewerStatus(Boolean doUpdate, List<Interviewer__c> lstInterviewers, String status){

        List<Interviewer__c> lstInterviewersUpdated = new List<Interviewer__c>();
        
        for (Interviewer__c interviewer : lstInterviewers) {
            interviewer.Status__c = status;
            lstInterviewersUpdated.add(interviewer);
        }

        if(doUpdate){
            update lstInterviewersUpdated;
        }
        return lstInterviewersUpdated;
    }
}