force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Country_List__c.field-meta.xml
<CustomField>
    <fullName>Country_List__c</fullName>
    <label>Country List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>Número do documento do candidato.</description>
    <inlineHelpText>Number document of candidate - Comprovante de Pessoa Física</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Current_Employer__c.field-meta.xml
<CustomField>
    <fullName>Current_Employer__c</fullName>
    <label>Current Employer</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Currently_Employed__c.field-meta.xml
<CustomField>
    <fullName>Currently_Employed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Currently Employed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GED/HS Diploma</fullName>
            </value>
            <value>
                <fullName>BA/BS</fullName>
            </value>
            <value>
                <fullName>MA/MS/MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>JD</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Post Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Legacy_Candidate_Number__c.field-meta.xml
<CustomField>
    <fullName>Legacy_Candidate_Number__c</fullName>
    <externalId>true</externalId>
    <label>Legacy Candidate Number</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Mobile__c.field-meta.xml
<CustomField>
    <fullName>Mobile__c</fullName>
    <label>Mobile</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Should_Redirect__c.field-meta.xml
<CustomField>
    <fullName>Should_Redirect__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Should Redirect</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_1__c</fullName>
    <label>Street Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Street_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_2__c</fullName>
    <inlineHelpText>Caso o endereço for preenchido inserir o número aqui!</inlineHelpText>
    <label>Street Address 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Street_Address_3__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_3__c</fullName>
    <label>Street Address 3</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR - Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>AD - Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>AE - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>AF - Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>AG - Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>AM - Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>AO - Angola</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>AT - Austria</fullName>
    </customValue>
    <customValue>
        <fullName>AU - Australia</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>BA - Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>BB - Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>BD - Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>BE - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BF - Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>BG - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>BH - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>BI - Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>BJ - Benin</fullName>
    </customValue>
    <customValue>
        <fullName>BN - Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>BO - Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>BS - Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>BT - Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>BW - Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>BY - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>BZ - Belize</fullName>
    </customValue>
    <customValue>
        <fullName>CA - Canada</fullName>
    </customValue>
    <customValue>
        <fullName>CD - Democratic Republic of the Congo</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CandidateRestResource.cls
@RestResource(urlMapping='/Candidate/*')
global with sharing class CandidateRestResource {

    //método para obter o Candidato
    //
    //Para listar os candidatos, deve ser possível mostrar todos ou filtrar por um desses campos:
    //Email, Candidate Number, Currently Employed ou City (troquei Currently Employed por Current_Employer__c e adicionei por CPF)
    @HttpGet
    global static List<Candidate__c> doGet() {
          
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String candidateInfo = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
  
        //se for passado um dos parametros na url retorna UM registo
        if (!String.isEmpty(candidateInfo)) {

            List<Candidate__c> candidate = 
            [SELECT Id, Name, City__c, Country__c, Current_Employer__c, Currently_Employed__c,
                    Education__c, Email__c, First_Name__c, Last_Name__c, Legacy_Candidate_Number__c,
                    Mobile__c, Phone__c, State_Province__c, Street_Address_1__c, Street_Address_2__c,
                    Years_of_Experience__c, Zip_Postal_Code__c, CPF__c, Country_List__c,
                    Street_Address_3__c, Should_Redirect__c 
                FROM Candidate__c 
                WHERE 
                    (Id = :candidateInfo) OR 
                    (Email__c = :candidateInfo) OR 
                    (Name = :candidateInfo) OR 
                    (Current_Employer__c = :candidateInfo) OR 
                    (City__c = :candidateInfo) OR 
                    (CPF__c = :candidateInfo)
            ];

            return candidate;

        //se NÂO passar parametors retorn uma LISTA   
        } else {

            List<Candidate__c> listCandidate = 
            [SELECT Id, Name, City__c, Country__c, Current_Employer__c, Currently_Employed__c,
                    Education__c, Email__c, First_Name__c, Last_Name__c, Legacy_Candidate_Number__c,
                    Mobile__c, Phone__c, State_Province__c, Street_Address_1__c, Street_Address_2__c,
                    Years_of_Experience__c, Zip_Postal_Code__c, CPF__c, Country_List__c,
                    Street_Address_3__c, Should_Redirect__c 
                FROM Candidate__c
            ];
            return listCandidate;
        }
          
    }

    //método para inserir um candidato
    @HttpPost
    global static String doPost(String firstName, String lastName, String email, String mobile, String education,
                                String currentEmployer, Integer yearsOfExperience, String streetAddress1, 
                                String streetAddress2, String streetAddress3, String city, String stateProvince,
                                String zipPostalCode, String cpf, String country) {

        Candidate__c candidate = new Candidate__c();

        candidate.First_Name__c = firstName;
        candidate.Last_Name__c = lastName;
        candidate.Email__c = email;
        candidate.Mobile__c = mobile;
        candidate.Education__c = education;
        candidate.Current_Employer__c = currentEmployer;
        candidate.Years_of_Experience__c = yearsOfExperience;
        candidate.Street_Address_1__c = streetAddress1;
        candidate.Street_Address_2__c = streetAddress2;
        candidate.City__c = city;
        candidate.State_Province__c = stateProvince;
        candidate.Zip_Postal_Code__c = zipPostalCode;
        candidate.CPF__c = cpf;
        candidate.Country_List__c = country;
        candidate.Street_Address_3__c = streetAddress3;

        candidate.Should_Redirect__c = false;
        candidate.Currently_Employed__c = false;

        insert candidate;

        return candidate.Id;
    }

    //método para atualizar um candidato
    @HttpPut
    global static String doPut(String candidateId, String firstName, String lastName, String email, String mobile, String education,
                               String currentEmployer, Integer yearsOfExperience, String streetAddress1, String streetAddress2, String streetAddress3,
                               String city, String stateProvince, String zipPostalCode, String country, String cpf) {

                                
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        candidateId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

        Candidate__c candidate = new Candidate__c();

        candidate.Id = candidateId;
        candidate.First_Name__c = firstName;
        candidate.Last_Name__c = lastName;
        candidate.Email__c = email;
        candidate.Mobile__c = mobile;
        candidate.Education__c = education;
        candidate.Current_Employer__c = currentEmployer;
        candidate.Years_of_Experience__c = yearsOfExperience;
        candidate.Street_Address_1__c = streetAddress1;
        candidate.Street_Address_2__c = streetAddress2;
        candidate.City__c = city;
        candidate.State_Province__c = stateProvince;
        candidate.Zip_Postal_Code__c = zipPostalCode;
        candidate.CPF__c = cpf;
        candidate.Country_List__c = country;
        candidate.Street_Address_3__c = streetAddress3;

        candidate.Should_Redirect__c = false;
        candidate.Currently_Employed__c = false;
        
        upsert candidate;

        return candidate.Id;
    }

    //método para excluir um candidato
    @HttpDelete
    global static String doDelete() {

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String candidateInfo = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);

        Candidate__c candidate = [SELECT Id, Name FROM Candidate__c WHERE (Id = :candidateInfo) OR (Name = :candidateInfo) OR (CPF__c = :candidateInfo) LIMIT 1];
        String msg = 'Candidate '+ candidate.Name + ' deleted.';

        //Candidate__c candidate = new Candidate__c();
        //candidate.Id = candidateId;
        delete candidate;

        return msg;
    }
}