force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
            <value>
                <fullName>Generate Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTestDataFactory.cls
@isTest
public with sharing class JobApplicationTestDataFactory {

    //massa para criar UM único 
    public static Job_Application__c createJobApplication(Boolean doInsert, Id candId, Id posId, String status, String stage){
        
        Job_Application__c job = new Job_Application__c();
        job.Candidate__c = candId;
        job.Position__c = posId;
        job.Status__c = status;
        job.Stage__c = stage;

        if(doInsert){
            insert job;
        }
        return job;
    }

    //massa para criar LISTA 
    public static List<Job_Application__c> createJobApplicationList(Boolean doInsert, List<Candidate__c> lstCandidates, Id posId, String status, String stage){
        
        List<Job_Application__c> lstJobs = new List<Job_Application__c>();

        for (Candidate__c candidate : lstCandidates) {

            Job_Application__c job = new Job_Application__c();
            job.Candidate__c = candidate.Id;
            job.Position__c = posId;
            job.Status__c = status;
            job.Stage__c = stage;
            lstJobs.add(job);
        }

        if(doInsert){
            insert lstJobs;
        }
        return lstJobs;
    }

    //massa para atualizar UM único 
    public static Job_Application__c updateJobApplication(Boolean doUpdate, Job_Application__c job, String status, String stage){
        
        Job_Application__c jobUpdated = job;
        jobUpdated.Status__c = status;
        jobUpdated.Stage__c = stage;

        if(doUpdate){
            update jobUpdated;
        }
        return jobUpdated;
    }
    
    //massa para atualizar UM único job 'StartDate'
    public static Job_Application__c updateJobApplicationDate(Boolean doUpdate, Job_Application__c job, Date startDate){
    
        Job_Application__c jobUpdated = job;
        jobUpdated.Expected_Start_Date__c = startDate;

        if(doUpdate){
            update jobUpdated;
        }
        return jobUpdated;
    }   

    //massa para deletar UM único 
    public static void deleteJobApplication(Boolean doDelete, Job_Application__c job){

        if(doDelete){
            delete job;
        }
    }  
}