force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interviewer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Date_Time_Interview__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Interview__c</fullName>
    <label>Date and Time of Interview</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Job_Application__c.Stage__c</field>
            <operation>notEqual</operation>
            <value>New, Phone Screen, Schedule Interviews, Closed - Position Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
            <value>
                <fullName>Generate Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InterviewerTest.cls
@isTest
public with sharing class InterviewerTest {

    //criação de registros
    @TestSetup
    static void createTestData() {
        Account acc = AccountTestDataFactory.createAccountSample(true);
        Contract contract = ContractTestDataFactory.createContract(true, acc.Id, 1, Date.today(),'New');
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Position__c position = PositionTestDataFactory.createPosition(true,acc.Id,'New','Pending');
        List<Candidate__c> lstCandidates = CandidateTestDataFactory.createCandidateList(true,10);
        List<Job_Application__c> lstJobs = JobApplicationTestDataFactory.createJobApplicationList(true, lstCandidates, position.Id, 'Open', 'New');
        List<Interviewer__c> lstInterviewers = InterviewerTestDataFactory.createInterviewerList(true,lstJobs, Datetime.now());
    }

    //
    @isTest
    static void testInterviewerUpdateCandidate() {

        List<Job_Application__c> lstJobs = [SELECT Id FROM Job_Application__c];

        Test.startTest();
        List<Interviewer__c> lstInterviewers = InterviewerTestDataFactory.createInterviewerList(true,lstJobs, Datetime.now()+10);
        Test.stopTest();

        List<Interviewer__c> lstInterviewersUpdated = [SELECT Id, Candidate__c FROM Interviewer__c WHERE Id IN :lstInterviewers];

        for (Interviewer__c interviewer : lstInterviewersUpdated) {
            Assert.areNotEqual(null, interviewer.Candidate__c);
        }
    }

    //
    @isTest
    static void testInterviewerVerifyDate() {

        List<Interviewer__c> lstInterviewers = [SELECT Id, Status__c,  Date_Time_Interview__c FROM Interviewer__c];
        List<Interviewer__c> lstInterviewersUpdated = new List<Interviewer__c>();

        try {
            Test.startTest();
            lstInterviewersUpdated = InterviewerTestDataFactory.updateInterviewerDate(true,lstInterviewers,Datetime.now()-1);
            Test.stopTest();  
        } catch (Exception error){
            Boolean result = error.getMessage().contains('The interview date and time must be greater than the current moment. Now:') ? true : false;
            Assert.areEqual(true, result);
        }
    }

    //
    @isTest
    static void testInterviewerUpdateJob() {

        List<Interviewer__c> lstInterviewers = [SELECT Id, Status__c,  Date_Time_Interview__c FROM Interviewer__c];
        List<Interviewer__c> lstInterviewersToUpdate = new List<Interviewer__c>();

        Test.startTest();
        lstInterviewersToUpdate = InterviewerTestDataFactory.updateInterviewerStatus(true,lstInterviewers,'Completed');
        Test.stopTest();

        List<Interviewer__c> lstInterviewersUpdated = [SELECT Id, Status__c, Job_Application__c, Job_Application__r.Status__c, Job_Application__r.Stage__c FROM Interviewer__c WHERE Id IN :lstInterviewersToUpdate];

        for (Interviewer__c interviewer : lstInterviewersUpdated) {
            Assert.areEqual('Open', interviewer.Job_Application__r.Status__c);
            Assert.areEqual('Interviews Completed', interviewer.Job_Application__r.Stage__c);
        }
    }

    //
    @isTest
    static void testInterviewerUpdateEquals() {

        List<Job_Application__c> lstJobs = [SELECT Id FROM Job_Application__c];

        try {
            Test.startTest();
            List<Interviewer__c> lstInterviewersNews = InterviewerTestDataFactory.createInterviewerList(true,lstJobs, Datetime.now());
            Test.stopTest();  
        } catch (Exception error){
            Boolean result = error.getMessage().contains('There is already an interview with the same Date and Time for this candidate') ? true : false;
            Assert.areEqual(true, result);
        }
    }
}