force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/Interviewer__c.object-meta.xml
<CustomObject>
    <label>Interviewer</label>
    <nameField>
        <displayFormat>INT-{0000}</displayFormat>
        <label>Interviewer No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviewers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Interviewer__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Date_Time_Interview__c.field-meta.xml
<CustomField>
    <fullName>Date_Time_Interview__c</fullName>
    <label>Date and Time of Interview</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Job_Application__c.field-meta.xml
<CustomField>
    <fullName>Job_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job Application</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Job_Application__c.Stage__c</field>
            <operation>notEqual</operation>
            <value>New, Phone Screen, Schedule Interviews, Closed - Position Closed</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Job_Application__c</referenceTo>
    <relationshipLabel>Interviewers</relationshipLabel>
    <relationshipName>Interviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Interviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
            <value>
                <fullName>Generate Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InterviewerTriggerHandler.cls
public with sharing class InterviewerTriggerHandler {
    
    //-----------------------------------------------------------------
    public InterviewerTriggerHandler() {
    }

    //-----------------------------------------------------------------
    //método para incluir o Candidato no registro Interview (assim aparece a lista relacionada de entrevista mas não precisa preencher pois no Job Application já tem essa informação)
    public void updateInterviewerCandidate(List<Interviewer__c> lstInterviewrs) {
        
        Set<Id> lstJobIds = new Set<Id>();
        for (Interviewer__c interviewer : lstInterviewrs) {
            if (interviewer.Job_Application__c != null) {
                lstJobIds.add(interviewer.Job_Application__c);
            }
        }

        Map<Id, Job_Application__c> mapJobs = new Map<Id, Job_Application__c>(
            [SELECT Id, Candidate__c 
            FROM Job_Application__c 
            WHERE Id IN :lstJobIds]
        );

        for (Interviewer__c interviewer : lstInterviewrs) {
            if (interviewer.Job_Application__c != null) {
                Job_Application__c job = mapJobs.get(interviewer.Job_Application__c);
                if (job != null) {
                    interviewer.Candidate__c = job.Candidate__c;
                }
            }
        }
    }

    //-----------------------------------------------------------------
    //método que verifica a data e hora de agora
    public void verifyInterviewerDate(List<Interviewer__c> lstInterviewrs) {
        
        for (Interviewer__c interviewer : lstInterviewrs) {
            
            Datetime dateNow = Datetime.now();
            Integer offset = UserInfo.getTimezone().getOffset(dateNow);
            Datetime dateLocal = dateNow.addSeconds(offset/1000);

            if (interviewer.Date_Time_Interview__c <= dateLocal) {
                interviewer.Date_Time_Interview__c.addError('The interview date and time must be greater than the current moment. Now: ' + dateLocal);
            }
        }
    }

    //-----------------------------------------------------------------
    //método para atualizar o registro de Job Application para entrevista completada
    public void updateInterviewerJob(List<Interviewer__c> lstInterviewrs) {
        
        Set<Id> lstJobIds = new Set<Id>();
        List<Job_Application__c> lstJobsToUpdate = new  List<Job_Application__c>();

        for (Interviewer__c interviewer : lstInterviewrs) {
            if (interviewer.Job_Application__c != null) {
                lstJobIds.add(interviewer.Job_Application__c);
            }
        }

        Map<Id, Job_Application__c> mapJobs = new Map<Id, Job_Application__c>(
            [SELECT Id, Candidate__c 
            FROM Job_Application__c 
            WHERE Id IN :lstJobIds]
        );

        for (Interviewer__c interviewer : lstInterviewrs) {
            if (interviewer.Job_Application__c != null) {
                if (interviewer.Status__c == 'Completed') {                    
                    Job_Application__c job = mapJobs.get(interviewer.Job_Application__c);
                    if (job != null) {
                        job.Status__c = 'Open';
                        job.Stage__c = 'Interviews Completed';
                        lstJobsToUpdate.add(job);
                    }
                }                
            }
        }

        if (lstJobsToUpdate != null & lstJobsToUpdate.size() > 0) {
            update lstJobsToUpdate;
        }
    } 

    //-----------------------------------------------------------------
    //método para verificar se a entrevista criada possui o mesmo candidato e data/hora   
    public void updateInterviewerEquals(List<Interviewer__c> lstInterviewrs) {

        //lista de date/time
        List<Datetime> lstInterviewrsDate = new List<Datetime>();
        for (Interviewer__c interviewr : lstInterviewrs) {
            lstInterviewrsDate.add(interviewr.Date_Time_Interview__c);
        }

        //query com as interviews com todas as interview
        List<Interviewer__c> lstInterviewrsSameDate = [
            SELECT Id, Date_Time_Interview__c, Candidate__c
            FROM Interviewer__c
            WHERE Date_Time_Interview__c IN :lstInterviewrsDate AND Id NOT IN :lstInterviewrs
        ];

        //for para ver se o candidato é o mesmo
        if (lstInterviewrsSameDate != null && lstInterviewrsSameDate.size() > 0) {
            for (Interviewer__c interviewr : lstInterviewrsSameDate) {
                for (Interviewer__c interviewrCurrent : lstInterviewrs) {
                    if (interviewr.Date_Time_Interview__c == interviewrCurrent.Date_Time_Interview__c) {
                        
                        if (interviewr.Candidate__c == interviewrCurrent.Candidate__c) {
                            interviewrCurrent.addError('There is already an interview with the same Date and Time for this candidate.');
                        }
                    }
                }
            }
        }
    }   
}