force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Street_Address_1__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_1__c</fullName>
    <label>Street Address 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Street_Address_2__c.field-meta.xml
<CustomField>
    <fullName>Street_Address_2__c</fullName>
    <inlineHelpText>Caso o endereço for preenchido inserir o número aqui!</inlineHelpText>
    <label>Street Address 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/IntegrationViaCEPCallout.cls
global with sharing class IntegrationViaCEPCallout {
   
    //Construtor vaizo
    public IntegrationViaCEPCallout() {

    }

    //cria lista e adiciona o valor retornado - apagado pois passamos um cep
    /*public static List<ViaCEP> getCEP(List<String> cepList){
    List<ViaCEP> returnValue = new List<ViaCEP>();
    returnValue.add(sendRequest(cepList.get(0)));

    return returnValue;
    }*/


    @future(callout = true)
    public static void getCEP(String endCEP, Id id){

        ViaCEP returnValue = sendRequest(endCEP);

        Candidate__c cand = new Candidate__c();
        cand.Id = id;
        cand.Street_Address_1__c = returnValue.logradouro;
        cand.Street_Address_2__c = returnValue.bairro;
        cand.State_Province__c = returnValue.uf;
        cand.City__c = returnValue.localidade;
        cand.Country__c = 'Brazil';
        update cand;        
    } 

    //Método http
    public static ViaCEP sendRequest(String cep){
        HttpRequest req = new HttpRequest();
        req.setEndpoint('https://viacep.com.br/ws/' + cep + '/json/');
        req.setMethod('GET');
        req.setHeader('Content-Type', 'application/json');
        req.setTimeout(120000);

        try {
            Http http = new Http();
            HttpResponse httpRes = http.send(req);
            if(httpRes.getStatusCode() == 200){
                return (ViaCEP) JSON.deserialize(httpRes.getBody(), ViaCEP.class);
            }
        } catch (Exception errorInteg) {
            return null;
        }
        return null;
    }

    global class ViaCEP {
    
        //Atributos
        public String cep;
        public String logradouro;
        public String complemento;
        public String bairro;
        public String localidade;
        public String uf;
    }
}