force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Country_List__c.field-meta.xml
<CustomField>
    <fullName>Country_List__c</fullName>
    <label>Country List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>Número do documento do candidato.</description>
    <inlineHelpText>Number document of candidate - Comprovante de Pessoa Física</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>Email</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR - Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>AD - Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>AE - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>AF - Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>AG - Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>AM - Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>AO - Angola</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>AT - Austria</fullName>
    </customValue>
    <customValue>
        <fullName>AU - Australia</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>BA - Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>BB - Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>BD - Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>BE - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BF - Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>BG - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>BH - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>BI - Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>BJ - Benin</fullName>
    </customValue>
    <customValue>
        <fullName>BN - Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>BO - Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>BS - Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>BT - Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>BW - Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>BY - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>BZ - Belize</fullName>
    </customValue>
    <customValue>
        <fullName>CA - Canada</fullName>
    </customValue>
    <customValue>
        <fullName>CD - Democratic Republic of the Congo</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CandidateController.cls
public with sharing class CandidateController {
  //
  @AuraEnabled
  public static Candidate__c createCandidate(
    String cpf,
    String firstName,
    String lastName,
    String email,
    String country,
    String cep
  ) {
    Candidate__c candidate = new Candidate__c();
    candidate.CPF__c = cpf;
    candidate.First_Name__c = firstName;
    candidate.Last_Name__c = lastName;
    candidate.Email__c = email;
    candidate.Country_List__c = country;
    candidate.Zip_Postal_Code__c = cep;

    insert candidate;

    return candidate;
  }
}