force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
            <value>
                <fullName>Generate Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/JobApplicationTest.cls
@isTest
public with sharing class JobApplicationTest {

    //criação de registros 
    @TestSetup
    static void createTestData() {
        Account acc = AccountTestDataFactory.createAccountSample(true);
        Contract contract = ContractTestDataFactory.createContract(true, acc.Id, 1, Date.today(),'New');
        Candidate__c candidate = CandidateTestDataFactory.createCandidateSample(true);
    }

    //
    @isTest
    static void testJobPostNew(){

        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Candidate__c candidate = [SELECT Id FROM Candidate__c LIMIT 1];
        Position__c position = PositionTestDataFactory.createPosition(true,accId,'New','Pending');

        Test.startTest();
        Job_Application__c job = JobApplicationTestDataFactory.createJobApplication(true,candidate.Id,position.Id,'Open','New');
        new JobApplicationTriggerHandler().postChatterJob(new Map<Id, Job_Application__c>(), new Map<Id, Job_Application__c>{job.Id => job});
        Test.stopTest();

        List<FeedItem> chatterPostsTest = [SELECT Id, Body FROM FeedItem LIMIT 1 ];
        Boolean result = chatterPostsTest[0].Body.contains('Nova Aplicação a vaga') ? true : false;
        Assert.areEqual(true, result);    
    }

    //
    @isTest
    static void testJobPostUpdate(){

        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Candidate__c candidate = [SELECT Id FROM Candidate__c LIMIT 1];
        Position__c position = PositionTestDataFactory.createPosition(true,accId,'New','Pending');
        Job_Application__c job = JobApplicationTestDataFactory.createJobApplication(true,candidate.Id,position.Id,'Open','New');

        Test.startTest();
        Job_Application__c jobUpdated = JobApplicationTestDataFactory.updateJobApplication(true,job,'Hold','Offer Extended');
        new JobApplicationTriggerHandler().postChatterJob(new Map<Id, Job_Application__c>{jobUpdated.Id => jobUpdated}, new Map<Id, Job_Application__c>{jobUpdated.Id => jobUpdated});
        Test.stopTest();

        List<FeedItem> chatterPostsTest = [SELECT Id, Body, CreatedDate FROM FeedItem];
        Boolean result = chatterPostsTest[1].Body.contains('Atualização da vaga aplicada') ? true : false;
        Assert.areEqual(true, result);    
    }

    //
    @isTest
    static void testJobStartDate(){

        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Candidate__c candidate = [SELECT Id FROM Candidate__c LIMIT 1];
        Position__c position = PositionTestDataFactory.createPosition(true,accId,'New','Pending');
        Job_Application__c job = JobApplicationTestDataFactory.createJobApplication(true,candidate.Id,position.Id,'Open','New');

        try {
            Test.startTest();
            Job_Application__c jobUpdated = JobApplicationTestDataFactory.updateJobApplicationDate(true,job,Date.today() + 20);
            Test.stopTest();  
        } catch (Exception error){
            Boolean result = error.getMessage().contains('Due to the hiring process, the start date must be MORE than 30 days from today! Inserted difference:') ? true : false;
            Assert.areEqual(true, result);
        }
    }

    //
    @isTest
    static void testJobDelete(){

        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Contract contract = [SELECT Id FROM Contract LIMIT 1];
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Candidate__c candidate = [SELECT Id FROM Candidate__c LIMIT 1];
        Position__c position = PositionTestDataFactory.createPosition(true,accId,'New','Pending');
        Job_Application__c job = JobApplicationTestDataFactory.createJobApplication(true,candidate.Id,position.Id,'Open','New');

        try {
            Test.startTest();
            JobApplicationTestDataFactory.deleteJobApplication(true, job);
            Test.stopTest();
        } catch (Exception error){
            Boolean result = error.getMessage().contains('For compliance reasons, once the vacancy has been applied under these conditions, the record cannot be deleted!') ? true : false;
            Assert.areEqual(true, result);
        }
    }

    @isTest
    static void testJobDAO(){

        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Contract contract = [SELECT Id FROM Contract WHERE AccountId = :accId  LIMIT 1];
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Candidate__c candidate = [SELECT Id, Name FROM Candidate__c LIMIT 1];
        Position__c position = PositionTestDataFactory.createPosition(true,accId,'New','Pending');
        Job_Application__c job = JobApplicationTestDataFactory.createJobApplication(true,candidate.Id,position.Id,'Open','New');

        Test.startTest();
        Job_Application__c jobGetId = JobApplicationDAO.searchJobById(job.Id);
        Job_Application__c jobGetIdDetails = JobApplicationDAO.searchJobByIdDetails(job.Id);
        List<Job_Application__c> lstJobCandidateId = JobApplicationDAO.searchJobByIdCandidate(candidate.Id);
        List<Job_Application__c> lstJobCandidateName = JobApplicationDAO.searchJobByNameCandidate(candidate.Name);
        Job_Application__c jobUpdated = JobApplicationTestDataFactory.updateJobApplication(true, job, 'Open', 'Interviews Completed');
        List<Job_Application__c> lstJobCandidateIdInterview = JobApplicationDAO.searchJobByIdCandidateAndInterview(candidate.Id);
        Test.stopTest();  

        Boolean jobFoundId = false;
        for (Job_Application__c jobs : lstJobCandidateId) {
            if (jobs.Id == job.Id) {
                jobFoundId = true;
                break;
            }
        }

        Boolean jobFoundName = false;
        for (Job_Application__c jobs : lstJobCandidateName) {
            if (jobs.Id == job.Id) {
                jobFoundName = true;
                break;
            }
        }

        Boolean jobFoundNameInterview = false;
        for (Job_Application__c jobs : lstJobCandidateIdInterview) {
            if (jobs.Id == jobUpdated.Id) {
                jobFoundNameInterview = true;
                break;
            }
        }

        Assert.areEqual(job.Id, jobGetId.Id);
        Assert.areEqual(job.Id, jobGetIdDetails.Id);
        Assert.areEqual(true, jobFoundId);
        Assert.areEqual(true, jobFoundName);
        Assert.areEqual(true, jobFoundNameInterview);
    }  
    
    @isTest
    static void testJobUpdateProposal(){

        Id accId = [SELECT Id FROM Account LIMIT 1].Id;
        Contract contract = [SELECT Id FROM Contract WHERE AccountId = :accId  LIMIT 1];
        Contract contractUpdated = ContractTestDataFactory.updateContractStatusFull(true, true, contract, 'Activated',1);
        Candidate__c candidate = CandidateTestDataFactory.createCandidateSample(true);
        Position__c position = PositionTestDataFactory.createPosition(true,accId,'New','Pending');

        Job_Application__c job = JobApplicationTestDataFactory.createJobApplication(true, candidate.Id, position.Id, 'Pending', 'Application');

        Test.startTest();
        Map<String, String> result = JobApplicationController.updateJobApplicationProposal(job.Id);
        Test.stopTest();

        job = [SELECT Id, Status__c, Stage__c FROM Job_Application__c WHERE Id = :job.Id];
        Assert.areEqual('Proposal', job.Status__c);
        Assert.areEqual('Generate Proposal', job.Stage__c);
    }

    @isTest
    public static void testSetDefaultValue() {

        String result1 = JobApplicationController.setDefaultValue('Test');
        Assert.areEqual('Test', result1);

        String result2 = JobApplicationController.setDefaultValue('');
        Assert.areEqual('TBD', result2);
    }

    @isTest
    public static void testFormatDate() {

        Date inputDate1 = Date.newInstance(2023, 11, 10);
        String result1 = JobApplicationController.formatDate(inputDate1);
        Assert.areEqual('10/11/2023', result1);

        Date inputDate2 = null;
        String result2 = JobApplicationController.formatDate(inputDate2);
        Assert.areEqual('TBD', result2);

        Date inputDate3 = Date.newInstance(2023, 1, 2);
        String result3 = JobApplicationController.formatDate(inputDate3);
        Assert.areEqual('02/01/2023', result3);
    }
}