force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Country_List__c.field-meta.xml
<CustomField>
    <fullName>Country_List__c</fullName>
    <label>Country List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/Job_Application__c.object-meta.xml
<CustomObject>
    <label>Job Application</label>
    <nameField>
        <displayFormat>APP-{00000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Application__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Candidate_Skills__c.field-meta.xml
<CustomField>
    <fullName>Candidate_Skills__c</fullName>
    <label>Candidate&apos;s Skills</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Expected_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Expected_Start_Date__c</fullName>
    <label>Expected Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Position</label>
    <referenceTo>Position__c</referenceTo>
    <relationshipLabel>Job Applications</relationshipLabel>
    <relationshipName>Job_Applications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salary</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Phone Screen</fullName>
            </value>
            <value>
                <fullName>Schedule Interviews</fullName>
            </value>
            <value>
                <fullName>Interviews Completed</fullName>
            </value>
            <value>
                <fullName>Offer Extended</fullName>
            </value>
            <value>
                <fullName>Closed - Rejected</fullName>
            </value>
            <value>
                <fullName>Closed - Accepted</fullName>
            </value>
            <value>
                <fullName>Closed - Declined</fullName>
            </value>
            <value>
                <fullName>Closed - Position Closed</fullName>
            </value>
            <value>
                <fullName>Generate Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Application__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
                <default>true</default>
                <label>Open</label>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/Position__c.object-meta.xml
<CustomObject>
    <label>Position</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Positions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Position__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Positions</relationshipLabel>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>Department</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Department</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Position__c/fields/Hiring_Manager__c.field-meta.xml
<CustomField>
    <fullName>Hiring_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hiring Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Positions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Position__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR - Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>AD - Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>AE - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>AF - Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>AG - Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>AM - Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>AO - Angola</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>AT - Austria</fullName>
    </customValue>
    <customValue>
        <fullName>AU - Australia</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>BA - Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>BB - Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>BD - Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>BE - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BF - Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>BG - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>BH - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>BI - Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>BJ - Benin</fullName>
    </customValue>
    <customValue>
        <fullName>BN - Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>BO - Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>BS - Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>BT - Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>BW - Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>BY - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>BZ - Belize</fullName>
    </customValue>
    <customValue>
        <fullName>CA - Canada</fullName>
    </customValue>
    <customValue>
        <fullName>CD - Democratic Republic of the Congo</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Department.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>IT</fullName>
    </customValue>
    <customValue>
        <fullName>Finance</fullName>
    </customValue>
    <customValue>
        <fullName>Support</fullName>
    </customValue>
    <customValue>
        <fullName>Sales</fullName>
    </customValue>
    <masterLabel>Department</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/JobApplicationController.cls
    public with sharing class JobApplicationController {

        @AuraEnabled
        public static Map<String, String> updateJobApplicationProposal(String idJob){

            Job_Application__c job = new Job_Application__c();
            job.Id = idJob;
            job.Status__c = 'Proposal';
            job.Stage__c = 'Generate Proposal';

            Job_Application__c getJob = JobApplicationDAO.searchJobByIdDetails(idJob);

            String salary = String.valueOf(getJob.Salary__c);
            String manager = (getJob.Position__r.Hiring_Manager__r.FirstName != null ? getJob.Position__r.Hiring_Manager__r.FirstName : 'Manager') + ' ' 
                                + getJob.Position__r.Hiring_Manager__r.LastName;

            String startDate = String.valueOf(getJob.Expected_Start_Date__c);
            String deadline = String.valueOf(getJob.Expected_Start_Date__c.addMonths(1));     
            
            String candidateName = getJob.Candidate__r.First_Name__c + (getJob.Candidate__r.Last_Name__c != null ? (' ' + getJob.Candidate__r.Last_Name__c) : '');
                    
            Map<String, String> response = new Map<String, String>();
            response.put('jobName', getJob.Name);
            response.put('city', getJob.Candidate__r.City__c);
            response.put('state', getJob.Candidate__r.State_Province__c);
            response.put('country', getJob.Candidate__r.Country_List__c);
            response.put('candidateNumber', getJob.Candidate__r.Name);
            response.put('candidateName', candidateName);
            response.put('positionName', getJob.Position__r.Name);
            response.put('accountName', getJob.Position__r.Account__r.Name);
            response.put('description', getJob.Position__r.Job_Description__c);
            response.put('skills', getJob.Candidate_Skills__c);
            response.put('department', getJob.Position__r.Department__c);
            response.put('salary', salary);
            response.put('manager', manager);
            response.put('startDate', startDate);
            response.put('deadline', deadline);
            
            try {
                update job;
                return response;
            } catch (Exception e) {
                throw new AuraHandledException('Error updating job application: ' + e.getMessage());
            }

        }
    }