force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>C-{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Country_List__c.field-meta.xml
<CustomField>
    <fullName>Country_List__c</fullName>
    <label>Country List</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Countries</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>Número do documento do candidato.</description>
    <inlineHelpText>Number document of candidate - Comprovante de Pessoa Física</inlineHelpText>
    <label>CPF</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Countries.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>BR - Brazil</fullName>
    </customValue>
    <customValue>
        <fullName>AD - Andorra</fullName>
    </customValue>
    <customValue>
        <fullName>AE - United Arab Emirates</fullName>
    </customValue>
    <customValue>
        <fullName>AF - Afghanistan</fullName>
    </customValue>
    <customValue>
        <fullName>AG - Antigua and Barbuda</fullName>
    </customValue>
    <customValue>
        <fullName>AL - Albania</fullName>
    </customValue>
    <customValue>
        <fullName>AM - Armenia</fullName>
    </customValue>
    <customValue>
        <fullName>AO - Angola</fullName>
    </customValue>
    <customValue>
        <fullName>AR - Argentina</fullName>
    </customValue>
    <customValue>
        <fullName>AT - Austria</fullName>
    </customValue>
    <customValue>
        <fullName>AU - Australia</fullName>
    </customValue>
    <customValue>
        <fullName>AZ - Azerbaijan</fullName>
    </customValue>
    <customValue>
        <fullName>BA - Bosnia and Herzegovina</fullName>
    </customValue>
    <customValue>
        <fullName>BB - Barbados</fullName>
    </customValue>
    <customValue>
        <fullName>BD - Bangladesh</fullName>
    </customValue>
    <customValue>
        <fullName>BE - Belgium</fullName>
    </customValue>
    <customValue>
        <fullName>BF - Burkina Faso</fullName>
    </customValue>
    <customValue>
        <fullName>BG - Bulgaria</fullName>
    </customValue>
    <customValue>
        <fullName>BH - Bahrain</fullName>
    </customValue>
    <customValue>
        <fullName>BI - Burundi</fullName>
    </customValue>
    <customValue>
        <fullName>BJ - Benin</fullName>
    </customValue>
    <customValue>
        <fullName>BN - Brunei</fullName>
    </customValue>
    <customValue>
        <fullName>BO - Bolivia</fullName>
    </customValue>
    <customValue>
        <fullName>BS - Bahamas</fullName>
    </customValue>
    <customValue>
        <fullName>BT - Bhutan</fullName>
    </customValue>
    <customValue>
        <fullName>BW - Botswana</fullName>
    </customValue>
    <customValue>
        <fullName>BY - Belarus</fullName>
    </customValue>
    <customValue>
        <fullName>BZ - Belize</fullName>
    </customValue>
    <customValue>
        <fullName>CA - Canada</fullName>
    </customValue>
    <customValue>
        <fullName>CD - Democratic Republic of the Congo</fullName>
    </customValue>
    <masterLabel>Countries</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/CandidateTriggerHandlerTest.cls
@isTest
public with sharing class CandidateTriggerHandlerTest {

    //testar novo candidato e o CPF se não for numérico
    @isTest
    static void testNewCandNumberCPF(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = 'teste';

        try{
            Test.startTest();
            insert candNew;
            Test.stopTest();

        } catch (Exception error){
            System.equals('O CPF só pode haver números. Sem letras, pontos e traços!', error.getMessage());
        }
    }

    //testar candidato atualizado e o CPF se não for numérico
    @isTest
    static void testUpCandNumberCPF(){
        
        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = '12345678909';

        insert candNew;

        candNew.CPF__c = 'teste';

        try{
            Test.startTest();
            update candNew;
            Test.stopTest();

        } catch (Exception error){
            System.equals('O CPF só pode haver números. Sem letras, pontos e traços!', error.getMessage());
        }
    }

    //testar novo candidato e  CPF se for menor que 11
    @isTest
    static void testNewCandMinCPF(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = '12345';

        try{
            Test.startTest();
            insert candNew;
            Test.stopTest();

        } catch (Exception error){
            System.equals('O CPF precisa ter 11 números!', error.getMessage());
        }
    }

    //testar candidato atualizado e CPF se for menor que 11
    @isTest
    static void testUpCandMinCPF(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = '22344123156';

        insert candNew;

        candNew.CPF__c = '12345';

        try{
            Test.startTest();
            update candNew;
            Test.stopTest();

        } catch (Exception error){
            System.equals('O CPF só pode haver números. Sem letras, pontos e traços!', error.getMessage());
        }
    }


    //testar novo candidato com o CPF inválido
    @isTest
    static void testNewCandValidCPF(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = '12345678999';

        try{
            Test.startTest();
            insert candNew;
            Test.stopTest();

        } catch (Exception error){
            System.equals('Este CPF não é válido!', error.getMessage());
        }
    }

    //testar atualizar o candidato com o CPF inválido
    @isTest
    static void testUpCandValidCPF(){
        
        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = '29588469970';

        insert candNew;

        candNew.CPF__c = '12345678999';

        try{
            Test.startTest();
            update candNew;
            Test.stopTest();

        } catch(Exception error) {
            System.equals('Este CPF não é válido!', error.getMessage());
        }
    }

    //testar novo candidato com CPF com único número
    @isTest
    static void testNewCandOnlyCPF(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.CPF__c = '11111111111';

        try {
            Test.startTest();
            insert candNew;
            Test.stopTest();

        } catch (Exception error) {
            System.equals('O CPF não pode ser composto por um único número!', error.getMessage());
        }
        
    }

    //testar novo candidato com cep menor que 8
    @isTest
    static void testNewNumCEP(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.Country_List__c = 'BR - Brazil';
        candNew.Zip_Postal_Code__c = '1234567';

        try {
            Test.startTest();
            insert candNew;
            Test.stopTest();

        } catch (Exception error) {
            System.equals('O CEP para o país Brasil deve conter 8 dígitos!', error.getMessage());
            
        }
    }

    //testar atualizar o candidato com cep menor que 8
    @isTest
    static void testUpNumCEP(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.Zip_Postal_Code__c = '04821010';

        insert candNew;

        candNew.Country_List__c = 'BR - Brazil';
        candNew.Zip_Postal_Code__c = '1234567';

        try {
            Test.startTest();
            update candNew;
            Test.stopTest();

        } catch (Exception error) {
            System.equals('O CEP para o país Brasil deve conter 8 dígitos!', error.getMessage());
            
        }
    }

    //testar novo candidato com o cep com letras
    @isTest
    static void testNewLetterCEP(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.Zip_Postal_Code__c = 'aaaaaaa1';

        try {
            Test.startTest();
            insert candNew;
            Test.stopTest();

        } catch (Exception error) {
            System.equals('No CEP não pode ser inserido letra ou ponto!', error.getMessage());
            
        }
    }

    //testar atualizar novo candidato com cep com letras
    @isTest
    static void testUpLetterCEP(){

        Candidate__c candNew = new Candidate__c();
        candNew.First_Name__c = 'Teste';
        candNew.Zip_Postal_Code__c = '04821010';

        insert candNew;

        candNew.Zip_Postal_Code__c = 'aaaaaaa1';

        try {
            Test.startTest();
            update candNew;
            Test.stopTest();

        } catch (Exception error) {
            System.equals('No CEP não pode ser inserido letra ou ponto!',error.getMessage());
            
        }
    }
}